import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, Bot, Shuffle, Zap, Check, X, Ghost, Crown, Instagram, Plus, Minus } from 'lucide-react';
import { UserPlan } from '../types';

interface LandingPageProps {
  onEnterApp: (plan?: UserPlan) => void;
  onViewLegal: (type: 'terms' | 'privacy') => void;
  isLoading?: boolean;
}

const LandingPage: React.FC<LandingPageProps> = ({ onEnterApp, onViewLegal, isLoading = false }) => {
  const observerRef = useRef<IntersectionObserver | null>(null);

  useEffect(() => {
    observerRef.current = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('animate-fade-in-up');
          entry.target.classList.remove('opacity-0', 'translate-y-10');
        }
      });
    }, { threshold: 0.1 });

    const elements = document.querySelectorAll('.reveal-on-scroll');
    elements.forEach((el) => observerRef.current?.observe(el));

    // Check for plan param to open pricing modal
    const params = new URLSearchParams(window.location.search);
    const plan = params.get('plan');
    if (plan && ['echo', 'clone', 'syndicate'].includes(plan)) {
      // Dispatch custom event to open pricing modal
      window.dispatchEvent(new CustomEvent('openPricing', { detail: plan }));
      // Clean URL
      window.history.replaceState({}, '', window.location.pathname);
    }

    return () => observerRef.current?.disconnect();
  }, []);

  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'yearly'>('monthly');

  const toggleFaq = (index: number) => {
    setOpenFaqIndex(openFaqIndex === index ? null : index);
  };

  const faqs = [
    {
        question: "How does GhostNote actually 'learn' my voice?",
        answer: "We analyze the syntax, vocabulary, sentence structures, and slang from your uploaded 'Brand DNA' files (PDFs, past articles, etc.). We then instruct our AI engine to apply those specific linguistic patterns to your new draft."
    },
    {
        question: "Is my uploaded data used to train the AI?",
        answer: "No. Absolutely not. Your data is processed securely via Google's Enterprise API for the sole purpose of generating your specific request. It is never used to train the base models or shared with other users."
    },
    {
        question: "How is this different from standard ChatGPT?",
        answer: "ChatGPT has a specific 'default' voice that sounds robotic and polite. GhostNote is built specifically for 'Style Transfer'. We prioritize *how* something is said over just *what* is said, allowing you to sound like a Gen Z intern, a professional CEO, or yourself."
    },
    {
        question: "Can I use the content for client work?",
        answer: "Yes. You retain full commercial ownership of all content generated by GhostNote. It is designed specifically to help freelancers and agencies scale their production."
    },
    {
        question: "What file formats do you support?",
        answer: "We support PDF, TXT, and CSV files for style references. The Clone plan allows file uploads up to 5MB, while the free Echo plan relies on text-paste references."
    },
    {
        question: "What happens if I cancel my subscription?",
        answer: "You can cancel at any time. You will retain access to your paid features until the end of your current billing cycle. After that, your account will revert to the free 'Echo' plan."
    }
  ];

  return (
    <div className="min-h-screen bg-background text-textMain font-sans overflow-x-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
            <div className="w-5 h-5 bg-white rounded-sm flex items-center justify-center">
               <div className="w-1.5 h-1.5 bg-black rounded-full" />
            </div>
            <span className="font-bold tracking-widest uppercase text-xs">GhostNote</span>
          </div>
          <div className="flex items-center gap-6">
             <button 
                onClick={() => !isLoading && onEnterApp('echo')} 
                disabled={isLoading}
                className="text-sm font-medium text-textMuted hover:text-white transition-colors hidden md:block disabled:opacity-50 disabled:cursor-not-allowed"
             >
                Log In
             </button>
             <button 
                onClick={() => !isLoading && onEnterApp('echo')}
                disabled={isLoading}
                className="bg-white text-black text-xs font-bold px-4 py-2 rounded hover:bg-gray-200 transition-colors uppercase tracking-wide disabled:opacity-50 disabled:cursor-not-allowed"
             >
                {isLoading ? 'Loading...' : 'Launch Now'}
             </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto flex flex-col items-center text-center">
          <div className="reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out">
            <div className="inline-block px-3 py-1 mb-6 border border-accent/20 rounded-full bg-accent/5">
               <span className="text-accent text-[10px] font-mono tracking-widest uppercase">The Linguistic DNA Engine</span>
            </div>
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 leading-[1.1]">
              Stop Sounding<br />Like a <span className="text-textMuted decoration-accent underline decoration-2 underline-offset-4">Robot</span>.
            </h1>
            <p className="text-lg md:text-xl text-textMuted max-w-2xl mx-auto mb-10 leading-relaxed font-light">
              The first AI that clones your "Linguistic DNA". Upload your past work. Generate new content that actually sounds like YOU.
            </p>
            <button 
              onClick={() => !isLoading && onEnterApp('clone')}
              disabled={isLoading}
              className="bg-accent text-black px-8 py-4 rounded-md font-bold text-sm md:text-base tracking-wide uppercase hover:bg-white hover:shadow-[0_0_20px_rgba(217,249,157,0.5)] transition-all flex items-center gap-2 mx-auto group disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Clone Your Voice Now <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
            </button>
          </div>

          {/* Comparison Visual */}
          <div className="mt-20 w-full max-w-4xl mx-auto reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-200">
             <div className="grid md:grid-cols-2 gap-0 border border-border rounded-xl overflow-hidden shadow-2xl bg-surface/50">
                <div className="p-8 border-b md:border-b-0 md:border-r border-border bg-black/50 text-left">
                   <div className="flex items-center gap-2 mb-4">
                      <Bot size={16} className="text-textMuted" />
                      <span className="text-xs font-mono text-textMuted uppercase">Generic Model</span>
                   </div>
                   <p className="text-textMuted leading-relaxed">
                      "In today's fast-paced digital landscape, it is imperative to leverage synergies to optimize key performance indicators. We are thrilled to announce..."
                   </p>
                </div>
                <div className="p-8 bg-surface relative text-left">
                   <div className="absolute top-0 left-0 w-1 h-full bg-accent"></div>
                   <div className="flex items-center gap-2 mb-4">
                      <div className="w-4 h-4 bg-accent rounded-full flex items-center justify-center">
                         <div className="w-1.5 h-1.5 bg-black rounded-full" />
                      </div>
                      <span className="text-xs font-mono text-accent uppercase">GhostNote Optimized</span>
                   </div>
                   <p className="text-white leading-relaxed font-medium">
                      "Look, the internet moves fast. If you're not stacking wins on your KPIs, you're dead in the water. That's why we shipped this feature."
                   </p>
                </div>
             </div>
          </div>
        </div>
      </section>

      {/* Pain Points */}
      <section className="py-24 border-t border-border/50 bg-black/50">
         <div className="max-w-7xl mx-auto px-6">
            <div className="grid md:grid-cols-3 gap-12">
               <div className="reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-100">
                  <div className="w-12 h-12 bg-surface border border-border rounded-lg flex items-center justify-center mb-6">
                     <Bot className="text-textMuted" />
                  </div>
                  <h3 className="text-xl font-bold mb-3">The GPT Slop</h3>
                  <p className="text-textMuted leading-relaxed text-sm">Generic models sound polite but boring. You lose readers instantly because your content feels synthesized and soulless.</p>
               </div>
               <div className="reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-200">
                  <div className="w-12 h-12 bg-surface border border-border rounded-lg flex items-center justify-center mb-6">
                     <Shuffle className="text-textMuted" />
                  </div>
                  <h3 className="text-xl font-bold mb-3">The Tone Switch</h3>
                  <p className="text-textMuted leading-relaxed text-sm">Switching between Client A's corporate tone and Client B's startup vibe is mentally exhausting. Burnout is real.</p>
               </div>
               <div className="reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-300">
                  <div className="w-12 h-12 bg-surface border border-accent rounded-lg flex items-center justify-center mb-6 shadow-[0_0_15px_-5px_rgba(217,249,157,0.3)]">
                     <Zap className="text-accent" />
                  </div>
                  <h3 className="text-xl font-bold mb-3 text-white">The GhostNote Fix</h3>
                  <p className="text-textMuted leading-relaxed text-sm">One-click style transfer. Your brand voice, preserved perfectly. Upload a PDF, set the intensity, and generate.</p>
               </div>
            </div>
         </div>
      </section>

      {/* How It Works */}
      <section className="py-32 px-6">
         <div className="max-w-4xl mx-auto">
            <div className="text-center mb-16 reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out">
               <h2 className="text-3xl font-bold mb-4">Workflow of the Future</h2>
               <p className="text-textMuted">Three steps to immortality.</p>
            </div>
            
            <div className="space-y-12">
               {[
                  { title: "Upload Brand DNA", desc: "Feed the engine PDFs, text files, or CSVs of your best work.", step: "01" },
                  { title: "Select Intensity", desc: "Dial in the mimicry from 'Loose Inspiration' (10%) to 'Exact Clone' (100%).", step: "02" },
                  { title: "Generate & Dominate", desc: "Get perfect drafts in seconds. Export to your CMS or send directly to the client.", step: "03" }
               ].map((item, i) => (
                  <div key={i} className="flex items-start gap-6 pb-12 border-b border-border last:border-0 reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out">
                     <span className="text-4xl font-mono text-border font-bold opacity-30">{item.step}</span>
                     <div>
                        <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                        <p className="text-textMuted">{item.desc}</p>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </section>

      {/* Pricing */}
      <section className="py-24 bg-surface/20 border-y border-border/50">
         <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-8 reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out">
               <h2 className="text-3xl font-bold mb-4">Choose Your Hardware</h2>
               <p className="text-textMuted">Scalable plans for freelancers and agencies.</p>
            </div>

            {/* Toggle Switch */}
            <div className="flex justify-center items-center gap-4 mb-12">
              <span className={`text-sm ${billingCycle === 'monthly' ? 'text-white font-bold' : 'text-gray-500'}`}>Monthly</span>
              
              <button 
                onClick={() => setBillingCycle(billingCycle === 'monthly' ? 'yearly' : 'monthly')}
                className="w-14 h-7 bg-gray-700 rounded-full relative transition-colors duration-300 focus:outline-none"
              >
                <div className={`absolute top-1 w-5 h-5 bg-accent rounded-full shadow-md transform transition-transform duration-300 ${
                  billingCycle === 'yearly' ? 'translate-x-8' : 'translate-x-1'
                }`} />
              </button>

              <span className={`text-sm ${billingCycle === 'yearly' ? 'text-white font-bold' : 'text-gray-500'}`}>
                Yearly <span className="text-accent text-xs ml-1">(SAVE 20%)</span>
              </span>
            </div>

            <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
               {/* Echo */}
               <div className="p-8 rounded-xl border border-border bg-background flex flex-col reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-100">
                  <div className="mb-6"><Ghost className="text-textMuted" /></div>
                  <h3 className="text-xl font-bold mb-2">The Echo</h3>
                  <div className="text-3xl font-bold mb-6">$0 <span className="text-sm font-normal text-textMuted">/ forever</span></div>
                  <ul className="space-y-3 mb-8 flex-1">
                     {['5 Credits / Day', 'Text Input Only', 'Standard Speed'].map((f, i) => (
                        <li key={i} className="flex gap-3 text-sm"><Check size={16} className="text-textMuted" /> {f}</li>
                     ))}
                  </ul>
                  <button onClick={() => onEnterApp('echo')} className="w-full py-3 border border-border rounded-md text-sm font-bold hover:bg-surface transition-colors uppercase tracking-wide">Start Free</button>
               </div>

               {/* Clone */}
               <div className="relative p-8 rounded-xl border-2 border-accent bg-surface/30 flex flex-col shadow-[0_0_40px_-10px_rgba(217,249,157,0.1)] transform md:-translate-y-4 reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-200">
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-accent text-black text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest">Most Popular</div>
                  <div className="mb-6"><Zap className="text-accent" /></div>
                  <h3 className="text-xl font-bold mb-2 text-white">The Clone</h3>
                  <div className="text-3xl font-bold mb-6">
                    {billingCycle === 'monthly' ? '$29' : '$244'} 
                    <span className="text-sm font-normal text-textMuted">/ {billingCycle === 'monthly' ? 'month' : 'year'}</span>
                  </div>
                  <ul className="space-y-3 mb-8 flex-1">
                     {['Unlimited Credits', 'Brand DNA File Upload', 'Tone Intensity Slider', 'Priority Generation'].map((f, i) => (
                        <li key={i} className="flex gap-3 text-sm"><Check size={16} className="text-accent" /> {f}</li>
                     ))}
                  </ul>
                  <button onClick={() => onEnterApp('clone')} className="w-full py-3 bg-accent text-black rounded-md text-sm font-bold hover:bg-white transition-colors uppercase tracking-wide">
                    {billingCycle === 'monthly' ? 'START 14-DAY FREE TRIAL' : 'START 14-DAY FREE TRIAL'}
                  </button>
                  {billingCycle === 'monthly' && (
                    <p className="text-xs text-gray-500 mt-2 text-center">$0.00 due today. Cancel anytime.</p>
                  )}
               </div>

               {/* Syndicate */}
               <div className="p-8 rounded-xl border border-purple-500/30 bg-background flex flex-col reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out delay-300">
                  <div className="absolute top-0 right-0 bg-purple-600 text-white text-xs font-bold px-3 py-1 rounded-bl-lg">
                    BEST VALUE
                  </div>
                  <div className="mb-6"><Crown className="text-purple-400" /></div>
                  <h3 className="text-xl font-bold mb-2">The Syndicate</h3>
                  <div className="text-3xl font-bold mb-6">
                    {billingCycle === 'monthly' ? '$99' : '$832'} 
                    <span className="text-sm font-normal text-textMuted">/ {billingCycle === 'monthly' ? 'month' : 'year'}</span>
                  </div>
                  <ul className="space-y-3 mb-8 flex-1">
                     {['Everything in Clone', 'Bulk CSV Processing', 'API Access', 'Concierge Support'].map((f, i) => (
                        <li key={i} className="flex gap-3 text-sm"><Check size={16} className="text-purple-400" /> {f}</li>
                     ))}
                  </ul>
                  <button onClick={() => onEnterApp('syndicate')} className="w-full py-3 bg-purple-600 text-white rounded-md text-sm font-bold hover:bg-purple-500 transition-colors uppercase tracking-wide">
                    UPGRADE NOW
                  </button>
                  {billingCycle === 'monthly' && (
                    <p className="text-xs text-gray-500 mt-2 text-center">$99.00 billed monthly</p>
                  )}
               </div>
            </div>
         </div>
      </section>

      {/* FAQs */}
      <section className="py-24 px-6 bg-surface/10">
         <div className="max-w-3xl mx-auto">
            <div className="text-center mb-16 reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out">
               <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
               <p className="text-textMuted">Everything you need to know about the engine.</p>
            </div>

            <div className="space-y-4">
               {faqs.map((faq, index) => (
                  <div 
                    key={index} 
                    className="border border-border rounded-lg bg-surface/40 overflow-hidden reveal-on-scroll opacity-0 translate-y-10 transition-all duration-700 ease-out"
                    style={{ transitionDelay: `${index * 100}ms` }}
                  >
                     <button 
                        onClick={() => toggleFaq(index)}
                        className="w-full p-6 text-left flex justify-between items-center hover:bg-surface/60 transition-colors"
                     >
                        <span className="font-bold text-sm md:text-base pr-4">{faq.question}</span>
                        {openFaqIndex === index ? (
                           <Minus size={18} className="text-accent shrink-0" />
                        ) : (
                           <Plus size={18} className="text-textMuted shrink-0" />
                        )}
                     </button>
                     <div 
                        className={`transition-all duration-300 ease-in-out overflow-hidden ${
                           openFaqIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                        }`}
                     >
                        <div className="p-6 pt-0 text-textMuted text-sm leading-relaxed border-t border-border/50">
                           {faq.answer}
                        </div>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-12 text-center">
         <div className="mb-6 flex justify-center items-center gap-6 text-sm font-medium text-textMuted">
            <a href="https://www.instagram.com/ghostnoteai" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors flex items-center gap-2">
               <Instagram size={18} />
               <span>Instagram</span>
            </a>
            <button onClick={() => onViewLegal('terms')} className="hover:text-white transition-colors">Terms of Service</button>
            <button onClick={() => onViewLegal('privacy')} className="hover:text-white transition-colors">Privacy Policy</button>
         </div>
         <p className="text-xs text-textMuted/50">© 2026 GhostNote AI. All rights reserved.</p>
      </footer>

      <style>{`
         .animate-fade-in-up {
            opacity: 1 !important;
            transform: translateY(0) !important;
         }
      `}</style>
    </div>
  );
};

export default LandingPage;