import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  type: 'terms' | 'privacy';
  onBack: () => void;
}

const LegalPage: React.FC<LegalPageProps> = ({ type, onBack }) => {
  const isTerms = type === 'terms';
  const title = isTerms ? "Terms of Service" : "Privacy Policy";
  const date = "Last Updated: January 2026";

  return (
    <div className="min-h-screen bg-background text-textMain font-sans animate-fade-in-up">
      {/* Header / Nav */}
      <div className="sticky top-0 z-50 bg-background/90 backdrop-blur-md border-b border-border">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <button 
            onClick={onBack}
            className="group flex items-center gap-2 text-sm font-bold text-textMuted hover:text-white transition-colors uppercase tracking-wide"
          >
            <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
            Back
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16 md:py-24">
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-white">{title}</h1>
          <p className="text-textMuted font-mono text-sm">{date}</p>
        </div>

        <div className="prose prose-invert prose-lg max-w-none prose-headings:text-white prose-p:text-textMuted prose-li:text-textMuted prose-strong:text-white">
          
          {isTerms ? (
            <>
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using GhostNote, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not use our service.
              </p>

              <h2>2. AI Disclaimer (Crucial)</h2>
              <ul>
                <li><strong>Accuracy:</strong> GhostNote uses Artificial Intelligence to generate text. AI can make mistakes ("hallucinations"). You are responsible for reviewing all output for accuracy before publishing.</li>
                <li><strong>Liability:</strong> We are not liable for any content you generate using our tool that may be offensive, inaccurate, or legally compromising.</li>
              </ul>

              <h2>3. Intellectual Property</h2>
              <ul>
                <li><strong>Your Input:</strong> You retain all rights to the text and files you upload.</li>
                <li><strong>The Output:</strong> You own the rights to the content generated by the AI for your account. You can use it for commercial purposes.</li>
              </ul>

              <h2>4. Subscriptions & Refunds</h2>
              <ul>
                <li><strong>Billing:</strong> Subscriptions are billed monthly via Stripe.</li>
                <li><strong>Cancellation:</strong> You may cancel at any time. You will retain access to your paid features until the end of your current billing cycle.</li>
                <li><strong>Refunds:</strong> Due to the high cost of AI processing, we do not offer refunds for partial months used, except where required by law.</li>
              </ul>

              <h2>5. Termination</h2>
              <p>
                We reserve the right to terminate accounts that use our AI for illegal activities, hate speech, or generating malicious spam.
              </p>
            </>
          ) : (
            <>
              <h2>1. Introduction</h2>
              <p>
                Welcome to GhostNote ("we", "our", or "us"). We are committed to protecting your personal information and your right to privacy. This policy explains how we handle your data when you use our AI writing services.
              </p>

              <h2>2. Data We Collect</h2>
              <ul>
                <li><strong>Personal Info:</strong> When you sign up, we collect your email address and authentication data via Google/Firebase.</li>
                <li><strong>Usage Data:</strong> We store the "Voice Profiles" and "Drafts" you save in our database to provide the service.</li>
                <li><strong>Payment Data:</strong> All payments are processed by Stripe. We do not store your full credit card number on our servers.</li>
              </ul>

              <h2>3. AI & Third-Party Processing</h2>
              <p>
                Our service utilizes the <strong>Google Gemini API</strong> to generate content.
              </p>
              <ul>
                <li>Your inputs (drafts and reference files) are sent to Google's servers for processing.</li>
                <li>According to Google's Enterprise Data terms, your data is <strong>not</strong> used to train their models when processed via the API.</li>
                <li>We do not sell your data to third parties.</li>
              </ul>

              <h2>4. Data Retention</h2>
              <p>
                You may delete your account and all associated data at any time by contacting support or using the "Delete Account" feature in your dashboard.
              </p>

              <h2>5. Contact Us</h2>
              <p>
                If you have questions about this policy, please contact us at: rizdigi.co@gmail.com
              </p>
            </>
          )}

          <div className="mt-12 pt-8 border-t border-border">
            <p className="text-sm text-textMuted/50">
              For any questions regarding these terms, please contact us at rizdigi.co@gmail.com
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalPage;